### ISSUE TITLE
[QUESTION] Repository Licensing

### ISSUE THREAD

**Issue by nicotravassos** [ACID-Solutions/starter#22]
Hi @Okipa,

I would like to use this repository within my portfolio at nicotravassos.co.za but unsure of licensing as my project is private. Is the licensing required to be displayed on my site under licensing, credits or is this not required and I can just include the licensing within my repository?

Please keep in mind I will not be cloning this project and not including the commits - I will be copying most of it as I do not require some parts.

**Comment by Okipa** [comment]
Hi @nicotravassos,

We are working on this project which is our app projects base.

As it is built on Laravel and with other open source packages, we currently chose to open-source it under MIT licence.

As so, you can use and release it as you want but you have to mention our company **ACID-Solutions** when you do it.

Thanks for questioning us about this.

**Comment by nicotravassos** [comment]
Thank you @Okipa.

Tell me when you say mention it me providing your name within private repository is alright or would you prefer me adding a credits page to my site?

Also could you guys perhaps add a live demo site with dummy admin user credentials?
