### ISSUE TITLE
[REQUEST] Demo

### ISSUE THREAD

**Issue by nicotravassos** [ACID-Solutions/starter#23]
Hi @Okipa,

Could you guys perhaps add a live demo of the site with dummy admin user credentials?

**Comment by Okipa** [comment]
Hi @nicotravassos,

We are thinking about it but this a decision which has a cost (server + time spent on it).

**Comment by nicotravassos** [comment]
Hi @Okipa,

You could use https://www.heroku.com/pricing where its free?

**Comment by Okipa** [comment]
Moreover, we are not sure there would be a particular interest for us to do that.

We currently are listing pros and cons, if we decide to add a demo site you'll see that in the readme !

Thanks for your interest.
